### ISSUE TITLE
Differences from CTC app

### ISSUE THREAD

**Issue by diomidov** [michel-kraemer/sudocle#2]
Here are some differences from the CTC app that I've noticed.

| Action | CTC | Sudocle |
|---|---|---|
| Alt | Corner mode | Colour mode |
| Ctrl+Shift | Colour mode | Nothing |
| Shift+Space | Previous mode | Centre mode |
| Number key while in colour mode | Colours the cell | Places a digit |
| Trying to add a number/color that's already in the cell | Removes the number | Nothing |
| Backspace in a cell with centre and corner clues | Clears centre unless in corner mode | Clears both |
| Corner/center mark with multiple selection | Or, unless all are present | Xor |
| Double-click | Selects all "similar" cells (where the meaning of "similar" depends on the contents of the cell and current mode) | Nothing, unless holding Alt |
| Shift-double-click | Adds all "similar" cells | Nothing |
| Shift+arrow/SD | Adds to selection | Nothing |
| Shift+click | Adds to selection | Nothing |
| Ctrl+click on selected cell | Removes from selection | Nothing |
| Ctrl+arrow/SD to an already selected cell | Doesn't move | Moves |
| Ctrl+I | Inverts selection | Nothing |
| Ctrl+Shift+Z | Undo | Redo |

**Comment by michel-kraemer** [comment]
Thanks for the overview!

Please only open an issue if you actually have a question, a problem, or a feature request. Thanks! :)
