### ISSUE TITLE
F-puzzles -> CTC ->Sudocle doesn't work. 

### ISSUE THREAD

**Issue by rewolff** [michel-kraemer/sudocle#245]
I got a sudoku from a booklet and wanted to solve it in an app. As I don't know how to enter puzzles into the CTC app, I entered it into f-puzzles and then used the bookmarklet to transfer it to CTC app (I don't like the f-puzzles solver interface). 

Then I came across sudocle and " just copy the puzzle’s ID from the CTC webapp and append it to the URL shown above." 
So I tried that and got: https://michelkraemer.com/sudocle/?puzzleid=fpuzzlesN4IgzglgXgpiBcBOANCA5gJwgEwQbT2AF9ljSSzKLryBdZQmq8l54%2Bx1p7rjtn%2FnQaCR3PgIm9hk0UM6zR4rssX0QAawgAbLTAwBjAIZo48QiH0wdYfCABKARgDCAJhCpHTgMwg1AN0MtAFdTEAB2EAoLKy0bM3tnABZ3excnZP9AkIRwyNJo61tPAFYUuzTSzODQhwA2PNBLQvjPeo9nCKrs%2BBAHCKim2KLnAA4y50RfVADqnLGBmLi8VKcxjzTJrtDkhebl8qc2lc7prJqABgaCoZa0nw8vbymQGe7en12b%2FbS3B9dn141fr5QZLBJOBxlNKQv4w%2ByJCEAs45Bw7EGLIqPZIeBEZU6zHpoxoYlqPUp%2FI52BHk%2BGHJEE95XUGY1ZlBFjLYo4HEvb2R6THFOTb4t4ONyfMFU%2F6Cnycnr1CVFYqIjy1RFy3oK9G8uzK372ZX3A3pelvebar7Gmm6ukavpMkn7ZURDzKjkimqQxUtZUC%2Bxqv12MJC02hSbe%2FZq%2FVBlX2YNuDUuS4R%2F1PDzBo12EZPRPii2StXY1OVD1zB06tWU4OU7M1pwnF7Inp1cuWuxql2p92NhlE66S4OdmPdwE5LU8tvZuFZ6X2RDq0s9c0TyXz6Pz2WLkDL%2FtFYNFmd4nui8e7lrB63ZkvHsOt1cmjzz6%2Bj5t5ldFeeU%2BcNl8gU%2FMlpszWOdWTtN8z32bNA3nYUby5O8WSHBEfybXpSiIWgiCAA%3D

this didn't work (empty grid). Then I removed the question mark as the example didn't have a question mark, and now my time is running at 11:45 while there is still a "loading...." displayed. 

While writing this I thought: Maybe the root-cause is the ctc app hanging when you query it for the puzzle. That's not the case: it gives a 404 puzzle not found without the question mark. (after a noticeable delay).

**Comment by michel-kraemer** [comment]
`puzzleid` is a parameter for the CTC app. In Sudocle, the parameter is called `fpuzzles`. Here's the correct link:

https://michelkraemer.com/sudocle/?fpuzzles=fpuzzlesN4IgzglgXgpiBcBOANCA5gJwgEwQbT2AF9ljSSzKLryBdZQmq8l54%2Bx1p7rjtn%2FnQaCR3PgIm9hk0UM6zR4rssX0QAawgAbLTAwBjAIZo48QiH0wdYfCABKARgDCAJhCpHTgMwg1AN0MtAFdTEAB2EAoLKy0bM3tnABZ3excnZP9AkIRwyNJo61tPAFYUuzTSzODQhwA2PNBLQvjPeo9nCKrs%2BBAHCKim2KLnAA4y50RfVADqnLGBmLi8VKcxjzTJrtDkhebl8qc2lc7prJqABgaCoZa0nw8vbymQGe7en12b%2FbS3B9dn141fr5QZLBJOBxlNKQv4w%2ByJCEAs45Bw7EGLIqPZIeBEZU6zHpoxoYlqPUp%2FI52BHk%2BGHJEE95XUGY1ZlBFjLYo4HEvb2R6THFOTb4t4ONyfMFU%2F6Cnycnr1CVFYqIjy1RFy3oK9G8uzK372ZX3A3pelvebar7Gmm6ukavpMkn7ZURDzKjkimqQxUtZUC%2Bxqv12MJC02hSbe%2FZq%2FVBlX2YNuDUuS4R%2F1PDzBo12EZPRPii2StXY1OVD1zB06tWU4OU7M1pwnF7Inp1cuWuxql2p92NhlE66S4OdmPdwE5LU8tvZuFZ6X2RDq0s9c0TyXz6Pz2WLkDL%2FtFYNFmd4nui8e7lrB63ZkvHsOt1cmjzz6%2Bj5t5ldFeeU%2BcNl8gU%2FMlpszWOdWTtN8z32bNA3nYUby5O8WSHBEfybXpSiIWgiCAA%3D

**Comment by rewolff** [comment]
Would it be an idea to substitute '\??puzzleid=' to nothing before further processing, to cater for stupidity like mine?

**Comment by rewolff** [comment]
I did not type that ^^^^^ . I Had a backslash before the first ?.

**Comment by michel-kraemer** [comment]
Yes, I think this should work. I'll keep this issue open and get back to you.

**Comment by michel-kraemer** [comment]
I've deployed a new version with support for the `puzzleid` parameter so both links above work now.
