### ISSUE TITLE
Grid and Symbols not clearly separated

### ISSUE THREAD

**Issue by meinradr** [michel-kraemer/sudocle#248]
In puzzle https://michelkraemer.com/sudocle/ghJHG6qMMH/ the plus between r2c3 and r2c4 is hard to differentiate between a minus since there is no margin around it.

**Comment by michel-kraemer** [comment]
I can see the difference very clearly:

<img width="60" alt="image" src="https://user-images.githubusercontent.com/295407/193410726-83948ee2-00db-4be1-a913-cb1462d6b00e.png">

What operating system and browser are you using? Also, what is your screen resolution?

**Comment by michel-kraemer** [comment]
By the way, the fpuzzles version seems to work a bit better:

https://michelkraemer.com/sudocle/?fpuzzles=fpuzzlesN4IgzglgXgpiBcBOANCALhNAbO8QEEAnTACwFsYMBjAAgEUBXaEVAQwbRIHtCEQyAdqzAYATCxCEGOMJT4A5HmVZYaYBgBMuAawY0pMmqwAOxrAE8AdDQAqAdy4BaKjCyqqEQlUMwB3rrI0aA40GhAA5pg0AgxkAEYwhGDIQSSEMDDOru6e3jBgNL7+gZzpMKERUTHxiWCWEuHEGggA2i2gAG4qDLgAjKiRHb4IaFIwqC4CaIkACkUQWACyrITaYK29ALoAvsjAu/t7B8dHp/ubyO0gXVg9CKIDEEMCI2MTvtOEc34Ly6vr8Baoh2ZxOh3BYO2FyuNzu8AAzI9nq8eu8prN5ksVmtWvCQRDQYSIdDOt1cAAWJHDeCjVEgSafb4eLH/Vrk/GQomQknXMkIACsVJeNLe9I+GJ+LJxgP5HK58vOl1Jt1wADYhSjxmL0V9MX9pS1VXKCSbuUreSqEAB2DUiukMiXM/UAlpW42c01HHmw3AADlttK1Dt1kudrV97oVZphfKQAdFwaZv2xLsQkc9ps2FxAK0IXDsrVAWAgAnyrWzLjcLpAACVegBhcSoOv1+EgfEgYull0V7LVlvk9sHTslsuA3tV1q1hv8iQt1VDvYj7vl96TwG10SNxdF0c9tdYftbtsdrtjloTw9TmtbwenversXrlqb+uz+8r8cHo/1hfNrdWjuy7npe/bwtuH4gd+17gW2zbgXew5nvuT5XhuNbgbO8G/nO4GAZBKGVmhL41laEFIQ+X6of2ZEnhRn4XtB6FkYhS7IY+RH9r65FsZRjHUde3FwbW3GsbuDGgYJb5ztxC4ERxfZSYgQHsVRnHXogPHiVBAnoZpdG8RJTEkZpYnAYRil6dJ8lqZZJk4TZ/HqVZ+H0Tpzn2b6Kl8ZJ6Hklp5kKc+tb+QZ2kWcFNb+YOzb+e+bkRcRtb8tuzYpWFgW2ZFKVmapTl2cl1kJUFSU1qqAV5b5JHlRllXGbW5W5T59WkUVhnuQVNbca57WJVx9ZeY5VW1mRcnFVlpVkT14Ulf2/ljb1s3Xv5rnZtMAAeaCFrpJHRXOoXtqgPp8AAvBIABmXBTPWfAAMQAAyPU9EiQLACD3ZYqrDh5IU4bF1lHbGIBnagl3XXdT3Pagr24B9X1Lj9UX1oB/1yYDlp4OtF1XWgN14A9kP3S90Cw5932dd1MkOejcLA9j4P44TRPQyT71kwjFMDVT+E07gIDrQAFPTuMQ4TxNvfAcPk5F3Fec23HKdmx14I4wt4yABOQ+LpPw6AiMK4dFq0zQJumwAlGrotayzEtSxzMv1jFIkA0bfMgyAYMi4zYs2zr0uldxTbOyevN8AA1Jb3vW+ArOS+zeudTVc7leIStA6roM4+rmtQzHtvxztDWO8nraG8rdOZwzGtM9rbO64XN6l/+EGh3gEeV171c+3nfv26Vx5zreZdA+3HtZ1bucw3X/s/lhr53q3ICj572c1770997Pg/U67p2R130dT3H9eIw2Tstu+i/uyvE+PbXx8z9eZ9zg2Ie75j+853f68P5vMFN7WcCqdF5Yw7qvbuR87YJ0iphXCxc04YwrmPKuX9mY9w3tA0qB1/rAPfkvT+a90G/0wf2HKc50rD0QRnZBndUH3ygQ3FKc8axkIQbTa+48o6T1jgwxGtE5xkVweXDhKDCGQILnw4uzZ+FsL5gAegIRAnhEjOpkWYSxSh7DFGH2USfVR0lpE73LnIoWYDb5oPEXoyKU0BFGPTto7h+crGTWRrYwai8LZmK4d/IhvDOr6TnJpIRI8HE+MsY/KywkaymU0W7UJFjdERPsswmJsjw7xPoSoyKmk/y1k0pfPBIjaFiMSX/FygS7GIKKeAnRTikl5K5s2TSPM8HL04QfRxfsKy5BwNtU+ACByGziMIGA2cABiEzJkSC4BwM84zJkTIyagOwEANCcDZoiEAJAYARBIFtOO8J6kXxfvA1AwzZDzIWdM2Zo5LlTK8R0nxKy1kkA2agbZuz9kfUOWUkiW4g6Nzfuc0Zd0FmLNQDM7AtzQVgqWSAZ56yDnvJ2eEPZGyjlD2bkCkZdzwUgEhXMmFVyHl0OWasxF3zkWfPRb818zCh7ZmBbisZ1yoWlmZXChFrykVbJRWig5GK/p0qGTiol9z8U3PZWKvFN9vFoK5W83l1KBW0owqlQBpdGWivxmCllELJUgp1bCklhCFU8o+air5lgfkkP/swhCIqLnSr1RKtlhqNa6s5eS7llKlWWppbavy6qkbYqdUa4lrrCXhvFbKx58rvWKotfy75Ry9r/VDe626nr9Vuo5Sa7uZrfVJqtTahu819ouyZc61lUaPXGpoTU3OhbrVUv9SqwNu0hVIxaVW6NeKCXQr7S62NpL4UJvNXyktRyKFpVOSAXtdaI0DqlUOr1LzE2ToDYwqRhUCkLqzfW5dmbs0NvMRIZtmzi1bsRknZsKdHXHsPQavNp65XnvHUWzd7aG6NRLhml9R6X0jtNR+ltfrk3WqOYI2x/7q05trQeiNwGC2gcvV+lNqqNGGNg6u+Dg7F0xvaaOi9raIOlskefNRD6APPrg6+uN7710TuVRhjtI0DHsbRvO7VBH+20dw/R4jqHSNTsw12mxWqw28ZdYBujyHo4kfA6JtjrU5bsZ7TxxD4rZMCfk024TSnr2cyiYHajdGdPSbXRSsDV7v36x3V1StmmT0Wa0zKojIGmOfpY5B1VsluZmYE65k9emnkGds6xhussAuScfUu/jln80KfC+h3zKnovy3rIrM5zmn25rkx5lDXmbOpfI/44NATYs0fy7pwryXitoZ82V7JDnKs5ak25mTCXOtWZ9SVprRyYlNKcx1lz3WQt1f0w1kTRmWspJ3vusbNXEuCc89ZxrbbIuIxyRUjTo28sIYm6Ior62Zt2fKyjBp7juP7fi8tnrSWpuncMwK7MYAuC3AwFdKcvQJBOzU0HZSqBcnCTnpdoOl255O2Er91AQOQBqZBxIXJ8PIcSAB39iQsOQBO1R1j5HEgg5qdBxIOe2OieY9QMJS7KOCeoGJ6TiQl34dO3J0zwndOQDCTU2TiQLP0eM9QNj+HQcna5Mu8JeHwkxf49QGj1AFOdhAA
